Improvements on ondemand clusters
- auto purge internal clusters when completed
- don't start cluster for ondemand jobs
- prevent multiple internal clusters for a single job

diff --git a/meta/prolog_magrathea_start b/meta/prolog_magrathea_start
--- a/meta/prolog_magrathea_start
+++ b/meta/prolog_magrathea_start
@@ -253,10 +253,12 @@ cleanup_magrathea_cluster()
 {
 	fetch_magrathea_status;
 #	if [ "$MAGRATHEA_STATUS" = "running-cluster" ]; then
+        if [ "$CLOUDTYPE" != "internal" ]; then
 		$ADMIN_COMMAND stopcluster $DOMAIN $JOBNAME $NCPU;
 		if [ $? -ne 0 ]; then
 			logger -p daemon.crit -t magrathea_prologue "Couldn't stop cluster.";
 		fi
+	fi
 #	fi
 
 	$ADMIN_COMMAND set-image $DOMAIN none
@@ -347,20 +349,24 @@ magrathea_start()
 	# check state each 10 seconds for 2 minutes total until in free state
 	for i in `seq 1 12`; do
 		fetch_magrathea_status;
-		[[ "$MAGRATHEA_STATUS" = "free" ]] && break;
+		if [ "$MAGRATHEA_STATUS" = "free" ] || [ "$MAGRATHEA_STATUS" = "free-bootable" ]; then
+			break;
+		fi
 		sleep 10;
 	done
 
 	fetch_magrathea_status;
-	if [ "$MAGRATHEA_STATUS" != "free" ]; then # still not online, try to cleanup
+	if [ "$MAGRATHEA_STATUS" != "free" ] && [ "$MAGRATHEA_STATUS" != "free-bootable" ]; then # still not online, try to cleanup
 		logger -p daemon.crit -t magrathea_prologue "Machine didn't switch to free state after force-boot.";
 		exit_with_rollback 1;
 	fi
 
-	$ADMIN_COMMAND startcluster $DOMAIN $JOBNAME $NCPU;
-	if [ $? -ne 0 ]; then # try to cleanup
-		logger -p daemon.crit -t magrathea_prologue "Couldn't start cluster after machine started.";
-		exit_with_rollback 1;
+	if [ "$CLOUDTYPE" != "internal" ]; then
+		$ADMIN_COMMAND startcluster $DOMAIN $JOBNAME $NCPU;
+		if [ $? -ne 0 ]; then # try to cleanup
+			logger -p daemon.crit -t magrathea_prologue "Couldn't start cluster after machine started.";
+			exit_with_rollback 1;
+		fi
 	fi
 
 	$ADMIN_COMMAND set-image $DOMAIN $ALTERNATIVE
