Scratch scripts improvements

diff --git a/meta/recheck_leftover_scratch b/meta/recheck_leftover_scratch
--- a/meta/recheck_leftover_scratch
+++ b/meta/recheck_leftover_scratch
@@ -18,7 +18,11 @@ function search_dirs
 		USER=$(basename $user_dir)
 		scr=$(dirname $user_dir)
 		user_sum=$(dead_quota_user_sum $user_dir)
-		$CACHE_UPDATE $SERVER "$USER@`hostname`:$scr" scratch_leftover $user_sum;
+
+		$CACHE_UPDATE $SERVER "$USER@`hostname`:$scr" scratch_leftover $user_sum >/dev/null 2>&1;
+		if [ $? -ne 0 ]; then
+			logger -p daemon.crit -t pbs_mom "Could not update leftover scratch for user \"$USER\".";
+		fi
 
 		UPDATED=1
 	done
@@ -36,21 +40,30 @@ for scr in $SCRATCHES; do
 		UPDATED=$(search_dirs $scr);
 
 		if [ "$UPDATED" -ne 0 ]; then
-			dead_quota_sum $scr >$scr/.dead.size
+			$(dead_quota_sum $scr >$scr/.dead.size) 2>/dev/null
 		fi
 
 	fi
 
 done
 
-$CACHE_LIST $SERVER scratch_leftover | grep $(hostname) | grep -v scratch.shared | cut -f1 | while read x; do
+# remove leftover records for directories previously removed
+SCRATCH_LEFTOVER=`$CACHE_LIST $SERVER scratch_leftover 2>/dev/null`;
+if [ $? -ne 0 ]; then
+	logger -p daemon.crit -t pbs_mom "Could not get pbs_cache information for leftover scratch.";
+fi
+
+echo $SCRATCH_LEFTOVER | grep $(hostname) | grep -v scratch.shared | cut -f1 | while read x; do
 
 	user=$(echo $x | cut -d@ -f1);
 	dir=$(echo $x | cut -d@ -f2 | cut -d: -f2);
 	sum=$(dead_quota_user_sum $dir/$user);
 
 	if [ -z $sum ] || [ $sum -eq 0 ]; then
-		$CACHE_DELETE $SERVER $x scratch_leftover
+		$CACHE_DELETE $SERVER $x scratch_leftover >/dev/null 2>&1
+		if [ $? -ne 0 ]; then
+			logger -p daemon.crit -t pbs_mom "Could not delete leftover scratch record for user \"$user\".";
+		fi
 	fi
 
 done
diff --git a/meta/report_scratch b/meta/report_scratch
--- a/meta/report_scratch
+++ b/meta/report_scratch
@@ -25,7 +25,10 @@ else
 	SCRATCHDEAD=0
 fi
 
-$CACHE_UPDATE $SERVER $HOSTNAME scratch_local $SCRATCHSIZE\;$SCRATCHDEAD
+$CACHE_UPDATE $SERVER $HOSTNAME scratch_local $SCRATCHSIZE\;$SCRATCHDEAD >/dev/null 2>&1
+if [ $? -ne 0 ]; then
+	logger -p daemon.crit -t pbs_mom "Reporting local scratch size to pbs_cache failed.";
+fi
 
 ######################
 # REPORT SSD SCRATCH #
@@ -48,4 +51,7 @@ else
 	SCRATCHDEAD=0
 fi
 
-$CACHE_UPDATE $SERVER $HOSTNAME scratch_ssd $SCRATCHSIZE\;$SCRATCHDEAD
+$CACHE_UPDATE $SERVER $HOSTNAME scratch_ssd $SCRATCHSIZE\;$SCRATCHDEAD >/dev/null 2>&1
+if [ $? -ne 0 ]; then
+	logger -p daemon.crit -t pbs_mom "Reporting SSD scratch size to pbs_cache failed.";
+fi
